[package]
name = "wallpaper-changer"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
windows = { version = "0.61.1", features = ["Win32_UI_WindowsAndMessaging"] }
tokio = { version = "1.45.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }